# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['dihedral_analyzer_1.3.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'MDAnalysis',
        'MDAnalysis.analysis',
        'MDAnalysis.analysis.dihedrals',
        'MDAnalysis.topology',
        'MDAnalysis.topology.tpr',
        'MDAnalysis.topology.GRO',
        'MDAnalysis.coordinates',
        'MDAnalysis.coordinates.TRR',
        'MDAnalysis.coordinates.base',
        'MDAnalysis.coordinates.GRO',
        'MDAnalysis.lib',
        'MDAnalysis.lib.formats',
        'MDAnalysis.lib.formats.libmdaxdr',
        'MDAnalysis.lib.formats.cython_util',
        'MDAnalysis.lib.formats.libmdaxdr_utils',
        'MDAnalysis.lib.formats.libmdaxdr_utils_cython',
        'MDAnalysis.lib.formats.libmdaxdr_cython',
        'MDAnalysis.lib.transformations',
        'MDAnalysis.lib._transformations',
        'MDAnalysis.lib.util',
        'MDAnalysis.lib.mdamath',
        'MDAnalysis.lib.distances',
        'MDAnalysis.lib.formats.libdcd',
        'MDAnalysis.lib.formats.libmda',
        'matplotlib.backends.backend_svg',
        'matplotlib.backends.backend_pdf',
        'matplotlib.backends.backend_ps',
        'matplotlib.backends.backend_agg',
        'tqdm',
        'tqdm.auto',
        'numpy',
        'scipy',
        'scipy.spatial',
        'scipy.spatial.distance',
        'argparse',
        'csv',
        'os',
        'sys',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='dihedral_analyzer_1.3_windows',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
) 